#!/usr/bin/env bash
# upgrade-guide-walk.sh
#
# Demo for campfireagent-a767 (re-implements campfireagent-73a to restore compile coverage).
# Verifies that docs/upgrade-0.19-to-0.30.md exists and that every Go code
# snippet it contains compiles correctly against the current campfire module.
#
# Strategy:
#   1. Confirm the guide document exists.
#   2. Parse ALL ```go fenced blocks from the guide.
#      - ```go,illustrative blocks are intentionally-broken "before" examples or
#        pseudo-code; they are skipped (not compiled).
#      - All other ```go blocks must compile.
#   3. Strip import declarations from each compilable block (the preamble provides
#      all needed imports).
#   4. Collect compilable snippets into a generated file inside the campfire module
#      (internal/upgrade_guide_snippets/), build once.
#   5. Report pass/fail.  Exit 1 if any snippet fails.
#
# Tagging convention (in the markdown):
#   ```go                — real after-example; MUST compile
#   ```go,illustrative   — intentionally broken or pseudo-code; SKIP
#
# Justification for ,illustrative tag (MUST meet ONE of):
#   a) References a removed/renamed API that genuinely cannot compile against 0.30.
#   b) Is comment-only narration (no real Go code).
#   c) Is intentionally pseudo-code with a literal "..." ellipsis or "{ ... }".
#   Anything else (real 0.30 API with undeclared vars) MUST be untagged —
#   the preamble handles common identifier declarations, import-stripping handles imports.
#
# Minimum compilable block count: 16 (baseline parity with hand-rolled checks pre #524).
# Total block floor: 30 (prevents accidental guide truncation).
#
# Exit codes:
#   0 — all checks pass
#   1 — one or more checks failed
#
# Usage:
#   bash cf-conventions/demos/upgrade-guide-walk.sh
#
# Run from the campfire repo root.

set -uo pipefail

# Locate the Go toolchain.
GO_BIN="$(which go 2>/dev/null || echo "")"
if [[ -z "$GO_BIN" ]]; then
  for candidate in /usr/local/go/bin/go ~/go/bin/go /usr/go/bin/go; do
    if [[ -x "$candidate" ]]; then
      GO_BIN="$candidate"
      break
    fi
  done
fi
if [[ -z "$GO_BIN" ]]; then
  echo "ERROR: go toolchain not found; ensure 'go' is on PATH or install at /usr/local/go"
  exit 1
fi

GUIDE="docs/upgrade-0.19-to-0.30.md"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMPDIR_BASE="$(mktemp -d)"
PARSER_SCRIPT="$TMPDIR_BASE/parser.py"

PASS=0
FAIL=0
SKIP=0

SNIPPET_PKG_DIR="$REPO_ROOT/internal/upgrade_guide_snippets"

cleanup() {
  rm -rf "$SNIPPET_PKG_DIR"
  rm -rf "$TMPDIR_BASE"
}
trap cleanup EXIT

ok()   { echo "  [PASS] $1"; PASS=$((PASS + 1)); }
fail() { echo "  [FAIL] $1"; FAIL=$((FAIL + 1)); }
skip() { echo "  [SKIP] $1"; SKIP=$((SKIP + 1)); }

# ---------------------------------------------------------------------------
# §A — Document existence
# ---------------------------------------------------------------------------
echo ""
echo "=== §A — Guide document existence ==="

GUIDE_PATH="$REPO_ROOT/$GUIDE"

if [[ -f "$GUIDE_PATH" ]]; then
  ok "upgrade guide exists at $GUIDE"
else
  fail "upgrade guide missing: $GUIDE"
  echo ""
  echo "RESULT: FAIL (guide not found — create it first)"
  exit 1
fi

# ---------------------------------------------------------------------------
# §B — Required sections present
# ---------------------------------------------------------------------------
echo ""
echo "=== §B — Required sections ==="

required_sections=(
  "BC-1"
  "BC-2"
  "BC-3"
  "BC-4"
  "BC-5"
  "BC-6"
  "BC-7"
  "BC-8"
  "BC-9"
  "BC-10"
  "BC-11"
  "BC-12"
  "BC-13"
  "BC-14"
  "BC-15"
  "BC-16"
  "BC-17"
  "BC-18"
  "Consumer: \`rd\`"
  "Consumer: \`dontguess\`"
  "Consumer: \`social\`"
  "Consumer: \`the reach\`"
  "Consumer: \`freeso\`"
  "Decision Tree"
  "Wire-Format Compatibility"
  "Compatibility Floor Summary"
)

for section in "${required_sections[@]}"; do
  if grep -qF "$section" "$GUIDE_PATH"; then
    ok "section '$section' present"
  else
    fail "section '$section' missing"
  fi
done

# ---------------------------------------------------------------------------
# §C — Parse ALL ```go fenced blocks and compile every non-illustrative one.
# ---------------------------------------------------------------------------
echo ""
echo "=== §C — Go snippet compilation (markdown parser) ==="

mkdir -p "$SNIPPET_PKG_DIR"
SNIPPET_FILE="$SNIPPET_PKG_DIR/snippets.go"

# Write the Go preamble for the snippets package.
cat > "$SNIPPET_FILE" <<'GOHEADER'
// Code generated by upgrade-guide-walk.sh — DO NOT EDIT.
// This file is generated during the demo run and deleted afterwards.
//
//go:build upgrade_guide_snippets

package snippets

import (
	"context"
	"crypto/ed25519"
	"fmt"
	"strings"
	"time"

	protocol    "github.com/campfire-net/campfire/cf-protocol/protocol"
	convention  "github.com/campfire-net/campfire/cf-conventions/cf-convention"
	cfsession   "github.com/campfire-net/campfire/cf-conventions/cf-session"
	cfdiscovery "github.com/campfire-net/campfire/cf-conventions/cf-discovery"
	"github.com/campfire-net/campfire/cf-conventions/cf-authority/trust"
)

// Suppress unused imports.
var (
	_ = context.Background
	_ = ed25519.PublicKey{}
	_ = fmt.Println
	_ = strings.HasPrefix
	_ = time.Hour
	_ = cfsession.KeyHandlingJail
	_ = cfdiscovery.ErrInviteOnly
	_ = trust.DenyExpired
	_ = convention.NewExecutor
	_ = protocol.Init
)

// Common preamble variables: identifiers that appear across snippets but would
// need to be declared in real consumer code.
var (
	ctx                 context.Context
	cfHomeDir           string
	id                  string
	campfireID          string
	client              *protocol.Client
	source              *protocol.Client
	dest                *protocol.Client
	checker             convention.ProvenanceChecker
	myProvenanceChecker convention.ProvenanceChecker
	messages            []protocol.Message
	workerPubKey        ed25519.PublicKey
	jailDir             string
	parentID            []byte
	childKey            []byte
	caps                []trust.Capability
	granterPubKey       []byte
)

// Suppress unused preamble vars (not all snippets use all of them).
var (
	_ = campfireID
	_ = jailDir
	_ = workerPubKey
	_ = messages
	_ = id
)

GOHEADER

# Write the Python parser to a temp file (avoids heredoc-in-heredoc issues
# and handles Unicode in the guide without encoding errors).
cat > "$PARSER_SCRIPT" << 'PYEOF'
#!/usr/bin/env python3
# upgrade-guide snippet extractor
# Usage: python3 parser.py <guide_path> <snippet_file>
#
# Extracts all ```go fenced blocks, skips illustrative-tagged ones,
# strips import declarations (preamble provides them), wraps real-code
# blocks in numbered functions, appends to the snippet file, and prints
# block counts as KEY=VALUE for the shell to read.

import sys
import re

guide_path  = sys.argv[1]
snippet_file = sys.argv[2]

with open(guide_path, encoding='utf-8') as f:
    lines = f.readlines()

blocks = []
in_block = False
block_tag = None
block_lines = []
start_line = 0

for i, line in enumerate(lines, 1):
    stripped = line.rstrip('\n')
    if not in_block:
        if stripped.startswith('```go'):
            # stripped[3:] is everything after 'go' on the fence line.
            # For '```go'            -> tag_suffix = ''              -> compilable
            # For '```go,illustrative' -> tag_suffix = ',illustrative' -> skip
            # For '```go '           -> tag_suffix = ' '             -> compilable
            tag_suffix = stripped[5:].strip()   # skip 'go' (5 chars: 3 backticks + 'go')
            # Wait - '```go' is 5 chars (backtick*3 = 3, 'g'=1, 'o'=1 = 5 total), so [5:] gives rest
            in_block = True
            block_tag = tag_suffix  # '' for plain ```go, ',illustrative' for tagged
            block_lines = []
            start_line = i
    else:
        if stripped == '```':
            blocks.append({
                'tag': block_tag,
                'lines': block_lines,
                'start': start_line,
                'end': i,
            })
            in_block = False
            block_lines = []
        else:
            block_lines.append(stripped)


def strip_imports(lines):
    """Remove import declarations from a block (single-line and block-form).
    The preamble provides all needed packages; redundant imports inside function
    bodies cause compile errors."""
    result = []
    in_import = False
    for line in lines:
        s = line.strip()
        if in_import:
            if s == ')':
                in_import = False
            continue
        if re.match(r'^import\s*\(', s):
            in_import = True
            continue
        if re.match(r'^import\s+(?:[a-zA-Z_][a-zA-Z0-9_]*)?\s*"[^"]*"', s):
            continue
        result.append(line)
    return result


# Pattern: a statement that is purely a qualified identifier (pkg.Name) followed
# by optional whitespace/comment.  Go disallows these as expression statements
# because the result is not used.  We prefix "_ = " to fix the "not used" error
# while preserving the snippet intent (showing that the identifier exists).
_STANDALONE_IDENT_RE = re.compile(
    r'^(?P<indent>\s*)(?P<expr>[a-zA-Z_][a-zA-Z0-9_]*(?:\.[a-zA-Z_][a-zA-Z0-9_]*)*)(?P<tail>\s*(?://.*)?)?$'
)


def suppress_unused_exprs(lines):
    """Prefix bare identifier expression statements with '_ = ' so they compile."""
    result = []
    for line in lines:
        m = _STANDALONE_IDENT_RE.match(line)
        if m:
            indent = m.group('indent')
            expr   = m.group('expr')
            tail   = m.group('tail') or ''
            # Only suppress if it looks like a package.Identifier (contains a dot)
            # and does NOT end with ) or } (would be a call/composite literal).
            if '.' in expr and not expr.endswith(')') and not expr.endswith('}'):
                line = f'{indent}_ = {expr}{tail}\n'
        result.append(line)
    return result


def has_real_code(lines):
    """Return True if block has at least one non-comment, non-empty line."""
    for line in lines:
        s = line.strip()
        if s and not s.startswith('//'):
            return True
    return False


total_go_blocks = len(blocks)
# A block is illustrative if its tag suffix starts with ',illustrative'
illustrative_count = sum(1 for b in blocks if b['tag'].startswith(',illustrative'))

compilable_blocks = []
for idx, b in enumerate(blocks, 1):
    if not b['tag'].startswith(',illustrative'):
        stripped = strip_imports(b['lines'])
        normalized = suppress_unused_exprs(stripped)
        if has_real_code(normalized):
            compilable_blocks.append((idx, normalized, b['start']))

with open(snippet_file, 'a', encoding='utf-8') as f:
    for (block_num, code_lines, start) in compilable_blocks:
        f.write(f'// snippet from block {block_num} (guide line {start})\n')
        f.write(f'func snippet_{block_num}() {{\n')
        for line in code_lines:
            f.write(line + '\n')
        f.write('}\n\n')

# Output for shell parsing (KEY=VALUE, no spaces, no special chars).
print(f"TOTAL_GO_BLOCKS={total_go_blocks}")
print(f"ILLUSTRATIVE_COUNT={illustrative_count}")
print(f"COMPILABLE_COUNT={len(compilable_blocks)}")
for idx, _, start in compilable_blocks:
    print(f"BLOCK_{idx}_LINE={start}")
PYEOF

# Run the parser and capture output.
PARSE_OUTPUT=$(python3 "$PARSER_SCRIPT" "$GUIDE_PATH" "$SNIPPET_FILE")
PARSE_EXIT=$?

if [[ $PARSE_EXIT -ne 0 ]]; then
  fail "markdown parser failed (python3 error) — check $PARSER_SCRIPT"
  echo ""
  echo "RESULT: FAIL (parser error)"
  exit 1
fi

# Parse KEY=VALUE output.
TOTAL_GO_BLOCKS=$(echo "$PARSE_OUTPUT" | grep '^TOTAL_GO_BLOCKS=' | cut -d= -f2)
ILLUSTRATIVE_COUNT=$(echo "$PARSE_OUTPUT" | grep '^ILLUSTRATIVE_COUNT=' | cut -d= -f2)
COMPILABLE_COUNT=$(echo "$PARSE_OUTPUT"   | grep '^COMPILABLE_COUNT='   | cut -d= -f2)
NON_ILLUSTRATIVE=$((TOTAL_GO_BLOCKS - ILLUSTRATIVE_COUNT))

echo "  Go blocks found: $TOTAL_GO_BLOCKS total / $NON_ILLUSTRATIVE non-illustrative / $ILLUSTRATIVE_COUNT illustrative (skipped)"
echo "  Snippets to compile: $COMPILABLE_COUNT"
echo ""

# Sanity check: total block floor.
MIN_GO_BLOCKS=30
if [[ "$TOTAL_GO_BLOCKS" -lt "$MIN_GO_BLOCKS" ]]; then
  fail "go block count below floor: found $TOTAL_GO_BLOCKS, expected >= $MIN_GO_BLOCKS — check guide for accidental deletions"
else
  ok "go block count: $TOTAL_GO_BLOCKS (>= $MIN_GO_BLOCKS floor)"
fi

# Minimum compilable block count (baseline parity).
MIN_COMPILABLE=16
if [[ "$COMPILABLE_COUNT" -lt "$MIN_COMPILABLE" ]]; then
  fail "compilable block count below baseline: found $COMPILABLE_COUNT, expected >= $MIN_COMPILABLE — check for illustrative over-tagging regression"
else
  ok "compilable block count: $COMPILABLE_COUNT (>= $MIN_COMPILABLE baseline)"
fi

if [[ "$COMPILABLE_COUNT" -eq 0 ]]; then
  ok "no non-illustrative snippets found — vacuously pass"
  skip "illustrative blocks: $ILLUSTRATIVE_COUNT (intentionally broken before-examples or pseudo-code, not compiled)"
else
  echo "  Building $COMPILABLE_COUNT snippets against 0.30 API ..."

  BUILD_OUT=$(cd "$REPO_ROOT" && "$GO_BIN" build -tags upgrade_guide_snippets ./internal/upgrade_guide_snippets/ 2>&1)
  BUILD_EXIT=$?

  if [[ $BUILD_EXIT -eq 0 ]]; then
    ok "all $COMPILABLE_COUNT snippets compile against 0.30 API"
  else
    echo "  Build error output:"
    echo "$BUILD_OUT" | sed 's/^/    /'
    echo ""
    fail "snippet compilation failed — see build output above"
    # Attribute errors to specific snippet functions where possible.
    while IFS= read -r errline; do
      if [[ "$errline" =~ snippet_([0-9]+) ]]; then
        snum="${BASH_REMATCH[1]}"
        fail "snippet from block $snum failed to compile"
      fi
    done <<< "$BUILD_OUT"
  fi

  skip "illustrative blocks: $ILLUSTRATIVE_COUNT (intentionally broken before-examples or pseudo-code, not compiled)"
fi

# ---------------------------------------------------------------------------
# §D — Key structural invariants in the guide text
# ---------------------------------------------------------------------------
echo ""
echo "=== §D — Guide structural invariants ==="

check_text() {
  local label="$1"
  local pattern="$2"
  if grep -qE "$pattern" "$GUIDE_PATH"; then
    ok "$label"
  else
    fail "$label — pattern '$pattern' not found in guide"
  fi
}

check_text "BC-1 import table present"    "pkg/campfire.*cf-protocol"
check_text "BC-2 WithNoWalkUp mentioned"   "WithNoWalkUp"
check_text "BC-3 GitHub transport removal" "TypeGitHub"
check_text "BC-4 JoinSession removed"      "JoinSession"
check_text "BC-5 cfs1_ deprecated"         "cfs1_"
check_text "BC-6 present_as removed"       "present_as"
check_text "BC-7 tagspec moved"            "tagspec"
check_text "BC-8 reserved tags listed"     "campfire:visibility-changed"
check_text "BC-9 GateEvaluator interface"  "GateEvaluator"
check_text "BC-10 ProvenanceCheckerV2"     "ProvenanceCheckerV2"
check_text "BC-11 predicate language"      "chain_to"
check_text "BC-12 ResolveChain"            "ResolveChain"
check_text "BC-13 lazy-mint"               "lazy-mint"
check_text "BC-14 cf-primitives binary"    "cf-primitives"
check_text "BC-15 argv0 dispatch"          "argv\[0\]"
check_text "BC-16 BridgeOptions.Forward"   "BridgeOptions\.Forward"
check_text "BC-17 HMAC derivation change"  "sign-fixed-input"
check_text "BC-18 GranterPubKey field 5"   "GranterPubKey"
check_text "consumer rd section"           "Consumer:.*rd"
check_text "consumer dontguess section"    "Consumer:.*dontguess"
check_text "consumer social section"       "Consumer:.*social"
check_text "consumer the reach section"    "Consumer:.*reach"
check_text "consumer freeso section"       "Consumer:.*freeso"
check_text "decision tree present"         "Decision Tree"
check_text "wire compat notes present"     "Wire-Format Compatibility"

# ---------------------------------------------------------------------------
# §E — Summary
# ---------------------------------------------------------------------------
echo ""
echo "=== §E — Summary ==="
TOTAL=$((PASS + FAIL + SKIP))
echo "  Checks: $TOTAL total / $PASS pass / $FAIL fail / $SKIP skip"
echo "  Compilable snippets: $COMPILABLE_COUNT (>= $MIN_COMPILABLE baseline required)"
echo ""

if [[ $FAIL -gt 0 ]]; then
  echo "RESULT: FAIL ($FAIL check(s) failed)"
  exit 1
else
  echo "RESULT: PASS — all checks passed ($COMPILABLE_COUNT blocks compile against 0.30 API)"
  exit 0
fi
