#!/usr/bin/env bash
# upgrade-guide-walk.sh
#
# Demo for campfireagent-901 / fix campfireagent-73a.
# Verifies that docs/upgrade-0.19-to-0.30.md exists and that every Go code
# snippet it contains compiles correctly against the current campfire module.
#
# Strategy:
#   1. Confirm the guide document exists.
#   2. Parse ALL ```go fenced blocks from the guide.
#      - ```go,illustrative blocks are intentionally-broken "before" examples;
#        they are skipped (not compiled).
#      - All other ```go blocks must compile.
#   3. Collect compilable snippets into a single generated file inside the
#      campfire module (internal/upgrade_guide_snippets/), wrap each in a
#      function, and build once.
#   4. Report pass/fail per snippet. Exit 1 if any snippet fails.
#
# Tagging convention (in the markdown):
#   ```go            — real after-example; MUST compile
#   ```go,illustrative — intentionally broken before-example; SKIP
#
# Exit codes:
#   0 — all checks pass
#   1 — one or more checks failed
#
# Usage:
#   bash cf-conventions/demos/upgrade-guide-walk.sh
#
# Run from the campfire repo root.

set -uo pipefail

# Locate the Go toolchain — prefer the standard install location.
GO_BIN="$(which go 2>/dev/null || echo "")"
if [[ -z "$GO_BIN" ]]; then
  for candidate in /usr/local/go/bin/go ~/go/bin/go /usr/go/bin/go; do
    if [[ -x "$candidate" ]]; then
      GO_BIN="$candidate"
      break
    fi
  done
fi
if [[ -z "$GO_BIN" ]]; then
  echo "ERROR: go toolchain not found; ensure 'go' is on PATH or install at /usr/local/go"
  exit 1
fi

GUIDE="docs/upgrade-0.19-to-0.30.md"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMPDIR_BASE="$(mktemp -d)"

PASS=0
FAIL=0
SKIP=0

SNIPPET_PKG_DIR="$REPO_ROOT/internal/upgrade_guide_snippets"

cleanup() {
  rm -rf "$SNIPPET_PKG_DIR"
  rm -rf "$TMPDIR_BASE"
}
trap cleanup EXIT

ok()   { echo "  [PASS] $1"; PASS=$((PASS + 1)); }
fail() { echo "  [FAIL] $1"; FAIL=$((FAIL + 1)); }
skip() { echo "  [SKIP] $1"; SKIP=$((SKIP + 1)); }

# ---------------------------------------------------------------------------
# §A — Document existence
# ---------------------------------------------------------------------------
echo ""
echo "=== §A — Guide document existence ==="

GUIDE_PATH="$REPO_ROOT/$GUIDE"

if [[ -f "$GUIDE_PATH" ]]; then
  ok "upgrade guide exists at $GUIDE"
else
  fail "upgrade guide missing: $GUIDE"
  echo ""
  echo "RESULT: FAIL (guide not found — create it first)"
  exit 1
fi

# ---------------------------------------------------------------------------
# §B — Required sections present
# ---------------------------------------------------------------------------
echo ""
echo "=== §B — Required sections ==="

required_sections=(
  "BC-1"
  "BC-2"
  "BC-3"
  "BC-4"
  "BC-5"
  "BC-6"
  "BC-7"
  "BC-8"
  "BC-9"
  "BC-10"
  "BC-11"
  "BC-12"
  "BC-13"
  "BC-14"
  "BC-15"
  "BC-16"
  "BC-17"
  "BC-18"
  "Consumer: \`rd\`"
  "Consumer: \`dontguess\`"
  "Consumer: \`social\`"
  "Consumer: \`the reach\`"
  "Consumer: \`freeso\`"
  "Decision Tree"
  "Wire-Format Compatibility"
  "Compatibility Floor Summary"
)

for section in "${required_sections[@]}"; do
  if grep -qF "$section" "$GUIDE_PATH"; then
    ok "section '$section' present"
  else
    fail "section '$section' missing"
  fi
done

# ---------------------------------------------------------------------------
# §C — Parse ALL ```go fenced blocks and compile every non-illustrative one.
#
# Parser (bash state machine):
#   - Scans line-by-line
#   - On ```go           → start collecting a compilable block
#   - On ```go,illustrative → start collecting, mark as skip
#   - On ``` (closing)   → end current block
#   - Any other ``` line  → ignored (```bash, ```toml, ```diff, ```json, etc.)
#
# For each compilable block:
#   - Ignore blocks whose only non-empty lines are comments (pure-comment
#     blocks have no API surface; they'd be empty function bodies).
#   - Wrap in a numbered function and append to snippets.go.
#   - Build the whole package once with -tags upgrade_guide_snippets.
# ---------------------------------------------------------------------------
echo ""
echo "=== §C — Go snippet compilation (markdown parser) ==="

mkdir -p "$SNIPPET_PKG_DIR"

SNIPPET_FILE="$SNIPPET_PKG_DIR/snippets.go"

# Write the file header once.
cat > "$SNIPPET_FILE" << 'GOHEADER'
// Code generated by upgrade-guide-walk.sh — DO NOT EDIT.
// This file is generated during the demo run and deleted afterwards.
//
//go:build upgrade_guide_snippets

package snippets

import (
	"context"
	"crypto/ed25519"
	"fmt"
	"strings"
	"time"

	cfprotocol "github.com/campfire-net/campfire/cf-protocol/protocol"
	convention  "github.com/campfire-net/campfire/cf-conventions/cf-convention"
	cfsession   "github.com/campfire-net/campfire/cf-conventions/cf-session"
	cfdiscovery "github.com/campfire-net/campfire/cf-conventions/cf-discovery"
	"github.com/campfire-net/campfire/cf-conventions/cf-authority/trust"
)

// Suppress unused imports.
var (
	_ = context.Background
	_ = ed25519.PublicKey{}
	_ = fmt.Println
	_ = strings.HasPrefix
	_ = time.Hour
	_ = cfprotocol.CampfireTagPrefix
	_ = convention.NewExecutor
	_ = cfsession.KeyHandlingJail
	_ = cfdiscovery.ErrInviteOnly
	_ = trust.DenyExpired
)

GOHEADER

# Parse markdown: extract all ```go blocks.
# State: in_go_block=0 (outside), in_go_block=1 (compiling), in_go_block=2 (illustrative/skip)
in_go_block=0
block_lines=()
block_num=0
snippet_labels=()
illustrative_count=0
total_go_blocks=0

while IFS= read -r line; do
  if [[ $in_go_block -eq 0 ]]; then
    # Look for opening fences.
    if [[ "$line" == '```go' ]]; then
      in_go_block=1
      block_lines=()
      total_go_blocks=$((total_go_blocks + 1))
    elif [[ "$line" == '```go,illustrative' ]]; then
      in_go_block=2
      block_lines=()
      total_go_blocks=$((total_go_blocks + 1))
      illustrative_count=$((illustrative_count + 1))
    fi
    # Any other ``` line — ignore (non-go fence or closing fence outside a block).
  else
    # Inside a block — check for closing fence.
    if [[ "$line" == '```' ]]; then
      if [[ $in_go_block -eq 1 ]]; then
        # Compilable block — check if it has any non-comment, non-empty lines.
        has_code=0
        for bl in "${block_lines[@]+"${block_lines[@]}"}"; do
          stripped="${bl#"${bl%%[![:space:]]*}"}"  # ltrim whitespace
          if [[ -n "$stripped" && "${stripped:0:2}" != "//" ]]; then
            has_code=1
            break
          fi
        done

        if [[ $has_code -eq 1 ]]; then
          block_num=$((block_num + 1))
          label="go-block-${total_go_blocks} (snippet ${block_num})"
          snippet_labels+=("$label")

          # Append function to snippets.go.
          printf 'func snippet_%d() {\n' "$block_num" >> "$SNIPPET_FILE"
          for bl in "${block_lines[@]+"${block_lines[@]}"}"; do
            printf '%s\n' "$bl" >> "$SNIPPET_FILE"
          done
          printf '}\n\n' >> "$SNIPPET_FILE"
        fi
        # Pure-comment or empty blocks: silently skip (they have no API surface).
      fi
      # illustrative blocks (in_go_block=2): already counted, no output needed.
      in_go_block=0
      block_lines=()
    else
      block_lines+=("$line")
    fi
  fi
done < "$GUIDE_PATH"

echo "  Go blocks found: $total_go_blocks total / $((total_go_blocks - illustrative_count)) non-illustrative / $illustrative_count illustrative (skipped)"
echo "  Snippets to compile: ${#snippet_labels[@]}"
echo ""

# Sanity check: the guide should have at least 30 go blocks (BC-1..BC-18 each have 1-3 blocks).
# If this drops below the floor, someone may have accidentally deleted blocks.
MIN_GO_BLOCKS=30
if [[ $total_go_blocks -lt $MIN_GO_BLOCKS ]]; then
  fail "go block count below floor: found $total_go_blocks, expected >= $MIN_GO_BLOCKS — check guide for accidental deletions"
else
  ok "go block count: $total_go_blocks (>= $MIN_GO_BLOCKS floor)"
fi

if [[ ${#snippet_labels[@]} -eq 0 ]]; then
  ok "no non-illustrative snippets found — all go blocks are comment-only or illustrative (vacuously pass)"
  skip "illustrative blocks: $illustrative_count (intentionally-broken before-examples, not compiled)"
else
  echo "  Building ${#snippet_labels[@]} snippets ..."

  BUILD_OUT=$(cd "$REPO_ROOT" && "$GO_BIN" build -tags upgrade_guide_snippets ./internal/upgrade_guide_snippets/ 2>&1)
  BUILD_EXIT=$?

  if [[ $BUILD_EXIT -eq 0 ]]; then
    for label in "${snippet_labels[@]}"; do
      ok "$label"
    done
  else
    echo "  Build error output:"
    echo "$BUILD_OUT" | sed 's/^/    /'
    echo ""
    # Attribute errors to specific snippets where possible.
    for label in "${snippet_labels[@]}"; do
      # Extract snippet number from label.
      snum="${label##*snippet }"
      snum="${snum%%)*}"
      if echo "$BUILD_OUT" | grep -q "snippet_${snum}[^0-9]"; then
        fail "$label (compile error — see build output above)"
      else
        fail "$label (compile error — see build output above)"
      fi
    done
  fi

  skip "illustrative blocks: $illustrative_count (intentionally-broken before-examples, not compiled)"
fi

# ---------------------------------------------------------------------------
# §D — Key structural invariants in the guide text
# ---------------------------------------------------------------------------
echo ""
echo "=== §D — Guide structural invariants ==="

check_text() {
  local label="$1"
  local pattern="$2"
  if grep -qE "$pattern" "$GUIDE_PATH"; then
    ok "$label"
  else
    fail "$label — pattern '$pattern' not found in guide"
  fi
}

check_text "BC-1 import table present"    "pkg/campfire.*cf-protocol"
check_text "BC-2 WithNoWalkUp mentioned"   "WithNoWalkUp"
check_text "BC-3 GitHub transport removal" "TypeGitHub"
check_text "BC-4 JoinSession removed"      "JoinSession"
check_text "BC-5 cfs1_ deprecated"         "cfs1_"
check_text "BC-6 present_as removed"       "present_as"
check_text "BC-7 tagspec moved"            "tagspec"
check_text "BC-8 reserved tags listed"     "campfire:visibility-changed"
check_text "BC-9 GateEvaluator interface"  "GateEvaluator"
check_text "BC-10 ProvenanceCheckerV2"     "ProvenanceCheckerV2"
check_text "BC-11 predicate language"      "chain_to"
check_text "BC-12 ResolveChain"            "ResolveChain"
check_text "BC-13 lazy-mint"               "lazy-mint"
check_text "BC-14 cf-primitives binary"    "cf-primitives"
check_text "BC-15 argv0 dispatch"          "argv\[0\]"
check_text "BC-16 BridgeOptions.Forward"   "BridgeOptions\.Forward"
check_text "BC-17 HMAC derivation change"  "sign-fixed-input"
check_text "BC-18 GranterPubKey field 5"   "GranterPubKey"
check_text "consumer rd section"           "Consumer:.*rd"
check_text "consumer dontguess section"    "Consumer:.*dontguess"
check_text "consumer social section"       "Consumer:.*social"
check_text "consumer the reach section"    "Consumer:.*reach"
check_text "consumer freeso section"       "Consumer:.*freeso"
check_text "decision tree present"         "Decision Tree"
check_text "wire compat notes present"     "Wire-Format Compatibility"

# ---------------------------------------------------------------------------
# §E — Summary
# ---------------------------------------------------------------------------
echo ""
echo "=== §E — Summary ==="
TOTAL=$((PASS + FAIL + SKIP))
echo "  Checks: $TOTAL total / $PASS pass / $FAIL fail / $SKIP skip"
echo ""

if [[ $FAIL -gt 0 ]]; then
  echo "RESULT: FAIL ($FAIL check(s) failed)"
  exit 1
else
  echo "RESULT: PASS — all checks passed"
  exit 0
fi
