// doclint checks that every exported symbol in the specified packages has
// a doc comment AND a corresponding Example_ test function.
//
// Usage:
//
//	go run ./scripts/doclint ./cf-protocol/protocol ./cf-conventions/cf-convention
//
// Exit 0 when all symbols pass both checks. Exit 1 when any symbol is missing
// a doc comment or an Example_ test. All findings are printed to stdout.
//
// Design: campfireagent-9e1 — Adversarial lint for SDK doc coverage.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: doclint <package-dir> [package-dir...]\n")
		os.Exit(2)
	}

	totalErrors := 0
	for _, dir := range os.Args[1:] {
		errors := checkPackage(dir)
		totalErrors += errors
	}

	if totalErrors > 0 {
		fmt.Printf("\ndoclint: %d issue(s) found\n", totalErrors)
		os.Exit(1)
	}
	fmt.Println("doclint: PASS — all exported symbols have doc comments and Example_ tests")
}

func checkPackage(dir string) int {
	// Resolve to absolute path.
	absDir, err := filepath.Abs(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "doclint: cannot resolve %s: %v\n", dir, err)
		return 1
	}

	fset := token.NewFileSet()

	// Parse production files (no _test.go).
	pkgs, err := parser.ParseDir(fset, absDir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "doclint: parse %s: %v\n", absDir, err)
		return 1
	}

	// Parse test files (only _test.go) to find Example_ functions.
	testPkgs, err := parser.ParseDir(fset, absDir, func(fi os.FileInfo) bool {
		return strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "doclint: parse test files in %s: %v\n", absDir, err)
		return 1
	}

	// Collect Example_ function names from test files.
	exampleNames := collectExamples(testPkgs)

	errors := 0
	for pkgName, pkg := range pkgs {
		fmt.Printf("=== Package %s ===\n", pkgName)

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				switch d := decl.(type) {
				case *ast.GenDecl:
					errors += checkGenDecl(d, exampleNames, pkgName)
				case *ast.FuncDecl:
					errors += checkFuncDecl(d, exampleNames, pkgName)
				}
			}
		}
	}
	return errors
}

// collectExamples returns a set of normalised symbol names covered by Example_ tests.
// We register multiple forms to support both Go-canonical naming conventions:
//   - Example_clientSend   → "clientsend" (camelCase, no separator)
//   - ExampleClient_Send   → "client_send" (godoc method example)
//
// Additionally we register the underscore-delimited form of any camelCase suffix
// so that Example_clientSend also covers "client_send".
func collectExamples(testPkgs map[string]*ast.Package) map[string]bool {
	names := make(map[string]bool)
	for _, pkg := range testPkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || fn.Name == nil {
					continue
				}
				name := fn.Name.Name
				if !strings.HasPrefix(name, "Example") {
					continue
				}
				// Strip "Example" prefix (and optional "_") to get the covered symbol.
				suffix := strings.TrimPrefix(name, "Example")
				suffix = strings.TrimPrefix(suffix, "_")

				// Register the plain lower-case form (e.g. "clientsend").
				lower := strings.ToLower(suffix)
				names[lower] = true

				// Also register the camelCase-to-underscore form so that
				// Example_clientSend covers the key "client_send" (generated by
				// symbolKey for method receivers).
				underscored := camelToUnderscore(suffix)
				if underscored != lower {
					names[underscored] = true
				}
			}
		}
	}
	return names
}

// camelToUnderscore converts a camelCase or PascalCase string to lower_snake_case.
// "clientSend" → "client_send", "HTTPTransport" → "h_t_t_p_transport" (not ideal
// but still a valid distinct key). The result is always lower-case.
func camelToUnderscore(s string) string {
	var out []rune
	runes := []rune(s)
	for i, r := range runes {
		if i > 0 && r >= 'A' && r <= 'Z' && runes[i-1] != '_' {
			out = append(out, '_')
		}
		out = append(out, []rune(strings.ToLower(string(r)))...)
	}
	return string(out)
}

// symbolKey returns a lower-case lookup key for a symbol name.
// For methods (receiver.Method), returns "receiver_method".
func symbolKey(receiver, name string) string {
	if receiver == "" {
		return strings.ToLower(name)
	}
	return strings.ToLower(receiver + "_" + name)
}

func checkGenDecl(d *ast.GenDecl, examples map[string]bool, pkgName string) int {
	errors := 0

	// Check block-level doc comment.
	hasBlockDoc := d.Doc != nil && len(d.Doc.List) > 0

	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.TypeSpec:
			if !ast.IsExported(s.Name.Name) {
				continue
			}
			// Doc may be on the block or on the spec.
			hasDoc := hasBlockDoc || (s.Comment != nil && len(s.Comment.List) > 0) ||
				(s.Doc != nil && len(s.Doc.List) > 0)
			if !hasDoc {
				fmt.Printf("  MISSING DOC: type %s\n", s.Name.Name)
				errors++
			}
			// Check for Example_.
			key := symbolKey("", s.Name.Name)
			if !examples[key] {
				fmt.Printf("  MISSING EXAMPLE: type %s (want Example_%s)\n", s.Name.Name, s.Name.Name)
				errors++
			}

		case *ast.ValueSpec:
			// Only report named exported vars/consts.
			for _, name := range s.Names {
				if !ast.IsExported(name.Name) {
					continue
				}
				// Doc may be on block, spec, or individual name comment.
				hasDoc := hasBlockDoc || (s.Comment != nil) || (s.Doc != nil)
				if !hasDoc {
					fmt.Printf("  MISSING DOC: %s %s\n", d.Tok, name.Name)
					errors++
				}
				// Constants and variables don't require individual Example_ tests
				// (they are typically demonstrated in type/function examples).
			}
		}
	}
	return errors
}

func checkFuncDecl(d *ast.FuncDecl, examples map[string]bool, pkgName string) int {
	if d.Name == nil || !ast.IsExported(d.Name.Name) {
		return 0
	}

	// Determine receiver type name.
	receiverType := ""
	if d.Recv != nil && len(d.Recv.List) > 0 {
		switch expr := d.Recv.List[0].Type.(type) {
		case *ast.StarExpr:
			if ident, ok := expr.X.(*ast.Ident); ok {
				receiverType = ident.Name
			}
		case *ast.Ident:
			receiverType = expr.Name
		}
	}

	// Skip methods on unexported receiver types — they implement interfaces
	// but are not part of the exported API surface.
	if receiverType != "" && !ast.IsExported(receiverType) {
		return 0
	}

	errors := 0

	// Doc comment check.
	if d.Doc == nil || len(d.Doc.List) == 0 {
		if receiverType != "" {
			fmt.Printf("  MISSING DOC: func (%s) %s\n", receiverType, d.Name.Name)
		} else {
			fmt.Printf("  MISSING DOC: func %s\n", d.Name.Name)
		}
		errors++
	}

	// Example_ test check.
	// We accept any of these key forms so both Example_ClientSend and
	// Example_clientSend style naming is recognised:
	//   1. "client_send"       — canonical form (receiver_method, underscore-joined)
	//   2. "clientsend"        — camelCase concatenated, fully lowercased
	//   3. "client_get_membership" — camelToUnderscore of full camelCase suffix
	key := symbolKey(receiverType, d.Name.Name)
	concatKey := strings.ToLower(receiverType + d.Name.Name)
	found := examples[key] || examples[concatKey]
	if !found {
		if receiverType != "" {
			fmt.Printf("  MISSING EXAMPLE: func (%s) %s (want Example_%s%s or Example_%s_%s)\n",
				receiverType, d.Name.Name, receiverType, d.Name.Name, receiverType, d.Name.Name)
		} else {
			fmt.Printf("  MISSING EXAMPLE: func %s (want Example_%s)\n",
				d.Name.Name, d.Name.Name)
		}
		errors++
	}

	return errors
}
